#!/usr/bin/env zsh

## arbitrarily large integer adder
alia() {
  # take input as strings
  local num1="$1" num2="$2" working out temp
  local -i num_ln neg1 neg2 is_sub sign w c b
  ([ -z "$num1" ] || [ -z "$num2" ]) && return 1
  # if num is neg, set flag and strip '-'
  [ ${num1::1} = '-' ] && {
    ((neg1++))
    num1=${num1:1}
  }
  [ ${num2::1} = '-' ] && {
    ((neg2++))
    num2=${num2:1}
  }
  # if one number is negative but the other isnt, treat as subtraction
  ((neg1!=neg2)) && {
    ((is_sub++))
  }
  # zero-pad shorter num
  ((${#num1}>=${#num2})) && {
    num_ln=${#num1}
    num2="${(l:num_ln::0:)num2}"
  } || {
    num_ln=${#num2}
    num1="${(l:num_ln::0:)num1}"
  }
  # if is sub, we take sign of larger num
  ((is_sub)) && {
    [[ "$num1" > "$num2" ]] && {
      ((neg1)) && ((sign++))
    }
    [[ "$num2" > "$num1" ]] && {
      ((neg2)) && ((sign++))
      temp="$num1"
      num1="$num2"
      num2="$temp"
    }
  }
  # if both are neg, output is neg
  (((neg1)) && ((neg2))) && ((sign++))
  # begin iteration over nums
  for ((i=num_ln; i>0; i--)); do
    ((is_sub)) && {
      w=$((num1[$i]-num2[$i]))
      ((b)) && {
        ((w--))
        ((b--))
      }
      ((w<0)) && {
        ((b++))
        ((w+=10))
      }
      true
    } || {
      w=$((num1[$i]+num2[$i]))
      ((c)) && {
        ((w++))
        ((c--))
      }
      ((w>=10)) && {
        ((c++))
        w=${w:1}
      }
    }
    out=""$w""$out""
  done
  # add last carry if needed
  ((c)) && out="1"$out""
  # strip unneeded zeros
  [[ ${out::1} = 0 ]] && {
    until [[ ${out::1} != '0' ]]; do
      ((${#out}==1)) && break
      out=${out:1}
    done
  }
  # add neg sign if needed
  ((sign)) && out="-"$out""
  # print result
  print -r "$out"
  # if ret_carry is set, return $c (for alfa); else return 0
  ! [ -z "$ret_carry" ] && {
    return $c
  } || {
    return 0
  }
}
