#!/usr/bin/env zsh

#### arithmetic functions ####

## arbitrarily large comparator
alcm() {
  local num1="$1" num2="$2" n1_macro n1_micro n2_macro n2_micro w1 w2 micro_ln num_ln
  local -i neg1 neg2
  # since we use return for result, use 0 to indicate invalid
  [[ -z "$num1" || -z "$num2" ]] && return 0
  # ensure nums are valid float
  [[ "$num1" != *'.'* ]] && num1=""$num1".0"
  [[ "$num2" != *'.'* ]] && num2=""$num2".0"
  # -0 and 0 are the same, so lets not confuse anything
  [[ "$num1" = '-0.0' ]] && num1='0.0'
  [[ "$num2" = '-0.0' ]] && num2='0.0'
  # handle negatives
  [[ ${num1::1} = '-' ]] && {
    ((neg1++))
    num1=${num1:1}
  }
  [[ ${num2::1} = '-' ]] && {
    ((neg2++))
    num2=${num2:1}
  }
  # if one num is neg but the other isnt we have our answer
  ((neg1)) && ! ((neg2)) && return 2
  ((neg2)) && ! ((neg1)) && return 1
  # strip leading zeros
  [[ ${num1::1} = 0 ]] && {
    until [[ ${num1::1} != '0' ]]; do
      num1=${num1:1}
    done
  }
  [[ ${num2::1} = 0 ]] && {
    until [[ ${num2::1} != '0' ]]; do
      num2=${num2:1}
    done
  }
  # adjust in case num was below zero decimal
  [[ ${num1::1} = '.' ]] && num1="0"$num1""
  [[ ${num2::1} = '.' ]] && num2="0"$num2""
  # separate int from decimal
  n1_macro=${num1%%.*}
  n1_micro=${num1#*.}
  n2_macro=${num2%%.*}
  n2_micro=${num2#*.}
  # right pad decimals with 0s until same length
  ((${#n1_micro}>=${#n2_micro})) && {
    micro_ln=${#n1_micro}
    n2_micro="${(r:micro_ln::0:)n2_micro}"
  } || {
    micro_ln=${#n2_micro}
    n1_micro="${(r:micro_ln::0:)n1_micro}"
  }
  # reconstruct num1 and num2 as integers
  num1=""$n1_macro""$n1_micro""
  num2=""$n2_macro""$n2_micro""
  # neg comparator
  ((neg1)) && {
    ((${#num1}>${#num2})) && return 2
    ((${#num1}<${#num2})) && return 1
    [[ "$num1" > "$num2" ]] && return 2
    [[ "$num1" < "$num2" ]] && return 1
  # pos comparator
  } || {
    ((${#num1}>${#num2})) && return 1
    ((${#num1}<${#num2})) && return 2
    [[ "$num1" > "$num2" ]] && return 1
    [[ "$num1" < "$num2" ]] && return 2
  }
  # if we've reached here, nums must be the same
  return 3
}

## arbitrarily large integer adder
alia() {
  # take input as strings
  local num1="$1" num2="$2" outvar=${3:-al_return} working out temp
  local -i num_ln neg1 neg2 is_sub sign w c b i
  [[ -z "$num1" || -z "$num2" ]] && return 1
  # treat 0 and -0 the same
  [[ "$num1" = '-0' ]] && num1=0
  [[ "$num2" = '-0' ]] && num2=0
  # if one num is 0, answer is other num
  [[ "$num1" = '0' ]] && {
    eval "$outvar=\"\$num2\""
    return 0
  }
  [[ "$num2" = '0' ]] && {
    eval "$outvar=\"\$num1\""
    return 0
  }
  # if num is neg, set flag and strip '-'
  [[ ${num1::1} = '-' ]] && {
    ((neg1++))
    num1=${num1:1}
  }
  [[ ${num2::1} = '-' ]] && {
    ((neg2++))
    num2=${num2:1}
  }
  # if one number is negative but the other isnt, treat as subtraction
  ((neg1!=neg2)) && {
    ((is_sub++))
  }
  # zero-pad shorter num
  ((${#num1}>=${#num2})) && {
    num_ln=${#num1}
    num2="${(l:num_ln::0:)num2}"
  } || {
    num_ln=${#num2}
    num1="${(l:num_ln::0:)num1}"
  }
  # if is sub, we take sign of larger num
  ((is_sub)) && {
    [[ "$num1" > "$num2" ]] && {
      ((neg1)) && ((sign++))
    }
    [[ "$num2" > "$num1" ]] && {
      ((neg2)) && ((sign++))
      temp="$num1"
      num1="$num2"
      num2="$temp"
    }
  }
  # if both are neg, output is neg
  ((neg1)) && ((neg2)) && ((sign++))
  # begin iteration over nums
  for ((i=num_ln; i>0; i--)); do
    ((is_sub)) && {
      w=$((num1[$i]-num2[$i]))
      ((b)) && {
        ((w--))
        ((b--))
      }
      ((w<0)) && {
        ((b++))
        ((w+=10))
      }
      true
    } || {
      w=$((num1[$i]+num2[$i]))
      ((c)) && {
        ((w++))
        ((c--))
      }
      ((w>=10)) && {
        ((c++))
        w=${w:1}
      }
    }
    out=""$w""$out""
  done
  # add last carry if needed
  ((c)) && [[ -z "$ret_carry" ]] && out="1"$out""
  # strip unneeded zeros
  [[ ${out::1} = 0 ]] && {
    until [[ ${out::1} != '0' ]]; do
      ((${#out}==1)) && break
      out=${out:1}
    done
  }
  # add neg sign if needed
  ((sign)) && out="-"$out""
  # assign result
  eval "$outvar=\"\$out\""
  # if ret_carry is set, return $c/$b (for alfa); else return 0
  ! [[ -z "$ret_carry" ]] && {
    ((is_sub)) && {
      return $((b+2))
    } || {
      return $c
    }
  } || {
    return 0
  }
}

## arbitrarily large integer subtractor
alis() {
  local num1="$1" num2="$2" outvar=${3:-al_return}
  [[ -z "$num1" || -z "$num2" ]] && return 1
  # invert sign of 2nd num
  [[ ${num2::1} = '-' ]] && {
    num2=${num2:1}
  } || {
    num2="-"$num2""
  }
  # feed to alia
  alia "$num1" "$num2" "$outvar"
}

## arbitrarily large float adder
alfa() {
  local num1="$1" num2="$2" outvar=${3:-al_return} num1_macro num1_micro num2_macro num2_micro macro micro alfa_out w10=1
  local -i micro_ln carry_val pad_ln
  [[ -z "$num1" || -z "$num2" ]] && return 1
  [[ "$num1" != *"."* ]] && num1=""$num1".0"
  [[ "$num2" != *"."* ]] && num2=""$num2".0"
  # treat 0.0 and -0.0 the same
  [[ "$num1" = '-0.0' ]] && num1=0.0
  [[ "$num2" = '-0.0' ]] && num2=0.0
  # if one num is 0.0, answer is other num
  [[ "$num1" = '0.0' ]] && {
    eval "$outvar=\"\$num2\""
    return 0
  }
  [[ "$num2" = '0.0' ]] && {
    eval "$outvar=\"\$num1\""
    return 0
  }
  # separate n1 and n2 into micro+macro
  num1_macro=${num1%%.*}
  num1_micro=${num1#*.}
  num2_macro=${num2%%.*}
  num2_micro=${num2#*.}
  # right-pad micros with 0s to ln of largest
  ((${#num1_micro}>=${#num2_micro})) && {
    micro_ln=${#num1_micro}
    num2_micro="${(r:micro_ln::0:)num2_micro}"
  } || {
    micro_ln=${#num2_micro}
    num1_micro="${(r:micro_ln::0:)num1_micro}"
  }
  # micros should have same sign as macros
  [[ ${num1_macro::1} = '-' ]] && num1_micro="-"$num1_micro""
  [[ ${num2_macro::1} = '-' ]] && num2_micro="-"$num2_micro""
  # add macro
  alia "$num1_macro" "$num2_macro" macro
  # add micro, handle carry
  ret_carry=1 alia "$num1_micro" "$num2_micro" micro
  carry_val=$?
  ((carry_val==1)) && {
    [[ ${macro::1} = '-' ]] && {
      macro=${macro:1}
      alia "$macro" 1 macro
      macro="-"$macro""
    } || {
      alia "$macro" 1 macro
    }
  }
  ((carry_val==3)) && {
    [[ ${macro::1} = '-' ]] && {
      macro=${macro:1}
      alia "$macro" -1 macro
      macro="-"$macro""
    } || {
      alia "$macro" -1 macro
    }
  }
  # handle fractional borrowing
  [[ ( ${macro::1} = '-' && ${micro::1} != '-' ) || ( ${micro::1} = '-' && ${macro::1} != '-' ) ]] && {
    [[ ${macro::1} = '-' ]] && {
      macro=${macro:1}
      alia "$macro" -1 macro
      macro="-"$macro""
    } || {
      alia "$macro" -1 macro
    }
    micro_ln=${#micro}
    pad_ln=$((micro_ln+1))
    w10="${(r:pad_ln::0:)w10}"
    [[ ${micro::1} = '-' ]] && {
      alia "$w10" "$micro" micro
    } || {
      micro="-"$micro""
      alia "$w10" "$micro" micro
    }
  }
  [[ ${micro::1} = '-' ]] && micro=${micro:1}
  # reassemble output
  alfa_out=""$macro"."$micro""
  [[ "$alfa_out" = "-0.0" ]] && alfa_out="0.0"
  eval "$outvar=\"\$alfa_out\""
}

## arbitrarily large float subtractor
alfs() {
  local num1="$1" num2="$2" outvar=${3:-al_return}
  [[ -z "$num1" || -z "$num2" ]] && return 1
  # invert sign of 2nd num
  [[ ${num2::1} = '-' ]] && {
    num2=${num2:1}
  } || {
    num2="-"$num2""
  }
  # feed to alfa
  alfa "$num1" "$num2" "$outvar"
}

## arbitrarily large integer multiplier
alim() {
  local num1="$1" num2="$2" alim_out='0' outvar=${3:-al_return} w1 w2 w carry='0' row=''
  local -i neg1 neg2 is_neg shft carryln row_ln j k
  [[ -z "$num1" || -z "$num2" ]] && return 1
  # handle multiply by zero
  [[ "$num1" = "0" || "$num2" = "0" || "$num1" = "-0" || "$num2" = "-0" ]] && {
    eval "$outvar=\"0\""
    return 0
  }
  # trim negs
  [[ ${num1::1} = '-' ]] && {
    num1=${num1:1}
    ((neg1++))
  }
  [[ ${num2::1} = '-' ]] && {
    num2=${num2:1}
    ((neg2++))
  }
  # handle negs
  ((neg1!=neg2)) && {
    ((is_neg++))
  }
  # outer loop - read num2 from r to l
  for ((j=${#num2}; j>0; j--)); do
    w2=$num2[$j]
    row=''
    carry='0'
    # inner loop - read num1 from r to l
    for ((k=${#num1}; k>0; k--)); do
      w1=$num1[$k]
      w=$(((w1*w2)+carry))
      ((${#w}==1)) && carry='0'
      ((${#w}>1)) && {
        carryln=$((${#w}-1))
        carry=${w::$carryln}
        w=${w:$carryln}
      }
      row=""$w""$row""
    done
    ((carry>0)) && row=""$carry""$row""
    # zero pad row equal to current shft
    row_ln=$((${#row}+$shft))
    row="${(r:row_ln::0:)row}"
    # add to total
    alia "$alim_out" "$row" alim_out
    ((shft++))
  done
  # handle neg sign
  ((is_neg)) && alim_out="-"$alim_out""
  eval "$outvar=\"\$alim_out\""
}

## arbitrarily large float multiplier
alfm() {
  local num1="$1" num2="$2" outvar=${3:-al_return} n1_micro n2_micro macro micro alfm_w alfm_out
  local -i neg1 neg2 is_neg deci_ln pad_ln
  [[ -z "$num1" || -z "$num2" ]] && return 1
  # ensure is valid float
  [[ "$num1" != *"."* ]] && num1=""$num1".0"
  [[ "$num2" != *"."* ]] && num2=""$num2".0"
  # fast exit on 0
  [[ "$num1" = '0.0' || "$num1" = '-0.0' || "$num2" = '0.0' || "$num2" = '-0.0' ]] && {
    eval "$outvar=\"0.0\""
    return 0
  }
  # handle negs
  [[ ${num1::1} = '-' ]] && {
    num1=${num1:1}
    ((neg1++))
  }
  [[ ${num2::1} = '-' ]] && {
    num2=${num2:1}
    ((neg2++))
  }
  # if one num neg but other not, result is neg
  ((neg1!=neg2)) && {
    ((is_neg++))
  }
  # separate decimals from integers
  n1_micro=${num1#*.}
  n2_micro=${num2#*.}
  # get decimal ln
  deci_ln=$((${#n1_micro}+${#n2_micro}))
  # conv num1 and num2 to integers
  num1=${num1//'.'/''}
  num2=${num2//'.'/''}
  # multiply using alim
  alim "$num1" "$num2" alfm_w
  # left-pad w with 0s if less than pad ln
  pad_ln=$((deci_ln+1))
  ((${#alfm_w}<pad_ln)) && {
    alfm_w="${(l:pad_ln::0:)alfm_w}"
  }
  # re-insert decimal
  deci_ln=$((${#alfm_w}-deci_ln))
  alfm_out=""${alfm_w::$deci_ln}"."${alfm_w:$deci_ln}""
  # handle neg sign
  ((is_neg)) && alfm_out="-"$alfm_out""
  eval "$outvar=\"\$alfm_out\""
}

## arbitrarily large integer divider
alid() {
  local num1="$1" num2="$2" outvar=${3:-al_return} alid_w out tmp prev_tmp
  local -i neg1 neg2 is_neg cmp l m
  [[ -z "$num1" || -z "$num2" ]] && return 1
  [[ "$num1" = '-0' ]] && num1=0
  [[ "$num2" = '-0' ]] && num2=0
  # err if divide by zero
  [[ "$num2" = '0' ]] && return 1
  # if num1 is 0, result and remainder will always be 0
  [[ "$num1" = '0' ]] && {
    al_rem=0
    [[ -z "$al_delim" ]] && {
      eval "$outvar=\"0\""
    } || {
      eval "$outvar=\"0_\${al_rem}\""
    }
    return 0
  }
  # handle negs
  [[ ${num1::1} = '-' ]] && {
    num1=${num1:1}
    ((neg1++))
  }
  [[ ${num2::1} = '-' ]] && {
    num2=${num2:1}
    ((neg2++))
  }
  ((neg1!=neg2)) && ((is_neg++))
  # if num1 is less than num2, exit with remainder
  alcm "$num1" "$num2"; cmp=$?
  ((cmp==2)) && {
    al_rem="$num1"
    [[ -z "$al_delim" ]] && {
      eval "$outvar=\"0\""
    } || {
      eval "$outvar=\"0_\${al_rem}\""
    }
    return 0
  }
  cmp=0
  # iterate num1 from l->r
  for ((l=1; l<=${#num1}; l++)); do
    alid_w=""$alid_w""$num1[$l]""
    # strip 0s
    ((${#alid_w}!=1)) && {
      until [[ ${alid_w::1} != '0' ]]; do
        ((${#alid_w}==1)) && break
        alid_w=${alid_w:1}
      done
    }
    # if num2 > w, write 0
    alcm "$alid_w" "$num2"; cmp=$?
    ((cmp==2)) && {
      out+="0"
      continue
    # else do long divide (guessing loop)
    } || {
      tmp="0"
      for ((m=1; m>0; m++)); do
        prev_tmp="$tmp"
        alia "$tmp" "$num2" tmp
        alcm "$tmp" "$alid_w"; cmp=$?
        ((cmp==1)) && {
          ((m--))
          out+="$m"
          break
        }
      done
      alis "$alid_w" "$prev_tmp" alid_w
    }
  done
  # strip 0s from out
  until [[ ${out::1} != '0' ]]; do
    ((${#out}==1)) && break
    out=${out:1}
  done
  # set neg if needed
  ((is_neg)) && out="-"$out""
  # set remainder to al_rem
  al_rem="$alid_w"
  # output result
  [[ -z "$al_delim" ]] && {
    eval "$outvar=\"\$out\""
  } || {
    eval "$outvar=\"\${out}_\${al_rem}\""
  }
}

## arbitrarily large modulo
almo() {
  local num1="$1" num2="$2" outvar=${3:-al_return} tmp_out al_rem
  alid "$num1" "$num2" tmp_out || return 1
  eval "$outvar=\"\$al_rem\""
}

## arbitrarily large float divider
alfd() {
  local num1="$1" num2="$2" outvar=${3:-al_return} n1_micro n2_micro n1_macro n2_macro macro micro al_scale=${al_scale:-20} next_dig out al_rem
  local -i neg1 neg2 is_neg cmp deci_ln n
  [[ -z "$num1" || -z "$num2" ]] && return 1
  # ensure valid float
  [[ "$num1" != *"."* ]] && num1=""$num1".0"
  [[ "$num2" != *"."* ]] && num2=""$num2".0"
  # treat -0.0 and 0.0 the same
  [[ "$num1" = '-0.0' ]] && num1='0.0'
  [[ "$num2" = '-0.0' ]] && num2='0.0'
  # handle 0s
  [[ "$num2" = "0.0" ]] && return 1
  [[ "$num1" = "0.0" ]] && {
    eval "$outvar=\"0.0\""
    return 0
  }
  # handle negs
  [[ ${num1::1} = '-' ]] && {
    ((neg1++))
    num1=${num1:1}
  }
  [[ ${num2::1} = '-' ]] && {
    ((neg2++))
    num2=${num2:1}
  }
  ((neg1!=neg2)) && ((is_neg++))
  # separate n1 and n2 into micro+macro
  n1_macro=${num1%%.*}
  n1_micro=${num1#*.}
  n2_macro=${num2%%.*}
  n2_micro=${num2#*.}
  # determine decimal maxln, 0-pad micros to maxln
  ((${#n1_micro}>=${#n2_micro})) && {
    deci_ln=${#n1_micro}
    n2_micro="${(r:deci_ln::0:)n2_micro}"
  } || {
    deci_ln=${#n2_micro}
    n1_micro="${(r:deci_ln::0:)n1_micro}"
  }
  # reassemble num1 and num2 as int
  num1=""$n1_macro""$n1_micro""
  num2=""$n2_macro""$n2_micro""
  # perform macro divide
  al_delim=1 alid "$num1" "$num2" macro
  al_rem=${macro#*_}
  macro=${macro%%_*}
  # decimal loop
  for ((n=0; n<al_scale; n++)); do
    [[ "$al_rem" = '0' ]] && break
    al_rem=""$al_rem"0"
    al_delim=1 alid "$al_rem" "$num2" next_dig
    al_rem=${next_dig#*_}
    next_dig=${next_dig%%_*}
    micro+="$next_dig"
  done
  # reassembly
  [[ -z "$micro" ]] && micro='0'
  out=""$macro"."$micro""
  ((is_neg)) && out="-"$out""
  # output result
  eval "$outvar=\"\$out\""
}

#### conversion functions ####

dat2bin() {
  local working="$1" outvar=${2:-al_return} out char
  local -i o
  for ((o=1; o<=${#working}; o++)); do
    char=$working[$o]
    print -v char -n -- ${(l{8}{0})$(([##2]#char))}
    out+="$char"
  done
  eval "$outvar=\"\$out\""
}

bin2dat() {
  local working="$1" char out outvar=${2:-al_return}
  local -i p
  for ((p=0; p<${#working}; p+=8)); do
    char=${working:$p:8}
    print -v char -n -- "\x"${(l{2}{0})$(([##16]2#$char))}""
    out+="$char"
  done
  eval "$outvar=\"\$out\""
}

bin2hex() {
  local bin="$1" outvar=${2:-al_return} out="" w hex
  local -i q b2h_rem pad_ln
  [[ -z "$bin" ]] && return 1
  # determine if padding is needed to make length a multiple of 4
  b2h_rem=$((${#bin}%4))
  ((b2h_rem)) && {
    pad_ln=$((${#bin}+4 - b2h_rem))
    bin="${(l:pad_ln::0:)bin}"
  }
  # read in 4-byte chunks
  for ((q=0; q<${#bin}; q+=4)); do
    w=${bin:$q:4}
    case "$w" in
      (0000) hex="0" ;;
      (0001) hex="1" ;;
      (0010) hex="2" ;;
      (0011) hex="3" ;;
      (0100) hex="4" ;;
      (0101) hex="5" ;;
      (0110) hex="6" ;;
      (0111) hex="7" ;;
      (1000) hex="8" ;;
      (1001) hex="9" ;;
      (1010) hex="a" ;;
      (1011) hex="b" ;;
      (1100) hex="c" ;;
      (1101) hex="d" ;;
      (1110) hex="e" ;;
      (1111) hex="f" ;;
      (*) return 1 ;;
    esac
    out+="$hex"
  done
  # strip leading zeros
  [[ ${out::1} = '0' ]] && {
    until [[ ${out::1} != '0' ]]; do
      ((${#out}==1)) && break
      out=${out:1}
    done
  }
  eval "$outvar=\"\$out\""
}

hex2bin() {
  local hex="$1" outvar=${2:-al_return} w bin out
  local -i r
  [[ -z "$hex" ]] && return 1
  # loop over hex, conv to bin
  for ((r=0; r<${#hex}; r++)); do
    w=${hex:$r:1}
    case "$w" in
      (0) bin="0000" ;;
      (1) bin="0001" ;;
      (2) bin="0010" ;;
      (3) bin="0011" ;;
      (4) bin="0100" ;;
      (5) bin="0101" ;;
      (6) bin="0110" ;;
      (7) bin="0111" ;;
      (8) bin="1000" ;;
      (9) bin="1001" ;;
      (a|A) bin="1010" ;;
      (b|B) bin="1011" ;;
      (c|C) bin="1100" ;;
      (d|D) bin="1101" ;;
      (e|E) bin="1110" ;;
      (f|F) bin="1111" ;;
      (*) return 1 ;;
    esac
    out+="$bin"
  done
  # strip leading zeros
  [[ ${out::1} = '0' ]] && {
    until [[ ${out::1} != '0' ]]; do
      ((${#out}==1)) && break
      out=${out:1}
    done
  }
  eval "$outvar=\"\$out\""
}

bin2dec() {
  local bin="$1" outvar=${2:-al_return} char b2d_out=0
  local -i s
  [[ -z "$bin" ]] && return 1
  for ((s=1; s<=${#bin}; s++)); do
    char=$bin[$s]
    alia "$b2d_out" "$b2d_out" b2d_out
    [[ "$char" = 1 ]] && alia "$b2d_out" "1" b2d_out
  done
  eval "$outvar=\"\$b2d_out\""
}

dec2bin() {
  local dec="$1" tmp_dec="$1" outvar=${2:-al_return} d2b_out d2b_rem
  [[ -z "$dec" ]] && return 1
  [[ "$dec" = '0' ]] && {
    eval "$outvar=\"0\""
    return 0
  }
  while [[ "$tmp_dec" != '0' ]]; do
    al_delim=1 alid "$tmp_dec" "2" tmp_dec
    d2b_rem=${tmp_dec#*_}
    tmp_dec=${tmp_dec%%_*}
    d2b_out=""$d2b_rem""$d2b_out""
  done
  eval "$outvar=\"\$d2b_out\""
}

hex2dec() {
  local hex="$1" outvar=${2:-al_return} h2d_tmp
  [[ -z "$hex" ]] && return 1
  hex2bin "$hex" h2d_tmp
  bin2dec "$h2d_tmp" "$outvar"
}

dec2hex() {
  local dec="$1" outvar=${2:-al_return} d2h_tmp
  [[ -z "$dec" ]] && return 1
  dec2bin "$dec" d2h_tmp
  bin2hex "$d2h_tmp" "$outvar"
}

#### logic functions ####

## bitmask
albm() {
  local bm_num="$1" mask="$2" outvar=${3:-al_return} cmp
  local -i is_neg
  [[ -z "$bm_num" || -z "$mask" ]] && return 1
  [[ ${mask::1} = '-' ]] && {
    ((is_neg++))
    mask=${mask:1}
    [[ ${bm_num::1} != '-' ]] && {
      bm_num="-"$bm_num""
    } || {
      bm_num=${bm_num:1}
    }
  }
  ! [[ -z "$hexmask" ]] && hex2dec "$mask" mask
  alcm "$bm_num" "$mask"; cmp=$?
  ((cmp==3)) && {
    ((is_neg)) && [[ "$bm_num" != '0' ]] && bm_num="-"$bm_num""
    eval "$outvar=\"\$bm_num\""
    return 0
  }
  alia "$mask" 1 mask
  [[ ${bm_num::1} = '-' ]] && {
    until [[ ${bm_num::1} != '-' ]]; do
      alia "$mask" "$bm_num" bm_num
    done
    ((is_neg)) && [[ "$bm_num" != '0' ]] && bm_num="-"$bm_num""
    eval "$outvar=\"\$bm_num\""
    return 0
  } || {
    almo "$bm_num" "$mask" bm_num
    ((is_neg)) && [[ "$bm_num" != '0' ]] && bm_num="-"$bm_num""
    eval "$outvar=\"\$bm_num\""
    return 0
  }
}

## rotate right
rrot() {
  local rrot_w="$1" rot_c=${2:-1} outvar=${3:-al_return}
  local -i t rot_ln
  [[ -z "$rrot_w" ]] && return 1
  dat2bin "$rrot_w" rrot_w
  rot_ln=$((${#rrot_w}-1))
  for ((t=0; t<rot_c; t++)); do
    rrot_w=""${rrot_w:$rot_ln}""${rrot_w::$rot_ln}""
  done
  bin2dat "$rrot_w" rrot_w
  eval "$outvar=\"\$rrot_w\""
}

## rotate left
lrot() {
  local lrot_w="$1" rot_c=${2:-1} outvar=${3:-al_return}
  local -i u
  [[ -z "$lrot_w" ]] && return 1
  dat2bin "$lrot_w" lrot_w
  for ((u=0; u<rot_c; u++)); do
    lrot_w=""${lrot_w:1}""${lrot_w::1}""
  done
  bin2dat "$lrot_w" lrot_w
  eval "$outvar=\"\$lrot_w\""
}

## shift right
rshft() {
  local rshft_w="$1" shft_c=${2:-1} outvar=${3:-al_return}
  local -i t shft_ln
  [[ -z "$rshft_w" ]] && return 1
  dat2bin "$rshft_w" rshft_w
  shft_ln=$((${#rshft_w}-1))
  for ((t=0; t<shft_c; t++)); do
    rshft_w="0"${rshft_w::$shft_ln}""
  done
  bin2dat "$rshft_w" rshft_w
  eval "$outvar=\"\$rshft_w\""
}

## shift left
lshft() {
  local lshft_w="$1" shft_c=${2:-1} outvar=${3:-al_return}
  local -i u
  [[ -z "$lshft_w" ]] && return 1
  dat2bin "$lshft_w" lshft_w
  for ((u=0; u<shft_c; u++)); do
    lshft_w=""${lshft_w:1}"0"
  done
  bin2dat "$lshft_w" lshft_w
  eval "$outvar=\"\$lshft_w\""
}

## bitwise XOR
alxor() {
  local num1="$1" num2="$2" outvar=${3:-al_return} cmp out
  local -i v pad_ln
  [[ -z "$num1" || -z "$num2" ]] && return 1
  # conv to binary
  dat2bin "$num1" num1
  dat2bin "$num2" num2
  # 0-pad to maxln if needed
  ((${#num1}>${#num2)) && {
    pad_ln=${#num1}
    num2="${(l:pad_ln::0:)num2}"
  }
  ((${#num1}<${#num2)) && {
    pad_ln=${#num2}
    num1="${(l:pad_ln::0:)num1}"
  }
  ((${#num1}==${#num2)) && pad_ln=${#num1}
  # loop through bits
  for ((v=1; v<=pad_ln; v++)); do
    [[ $num1[$v] != $num2[$v] ]] && {
      out+='1'
    } || {
      out+='0'
    }
  done
  bin2dat "$out" "$outvar"
}

## bitwise XNOR
alxnor() {
  local num1="$1" num2="$2" outvar=${3:-al_return} cmp out
  local -i v pad_ln
  [[ -z "$num1" || -z "$num2" ]] && return 1
  # conv to binary
  dat2bin "$num1" num1
  dat2bin "$num2" num2
  # 0-pad to maxln if needed
  ((${#num1}>${#num2)) && {
    pad_ln=${#num1}
    num2="${(l:pad_ln::0:)num2}"
  }
  ((${#num1}<${#num2)) && {
    pad_ln=${#num2}
    num1="${(l:pad_ln::0:)num1}"
  }
  ((${#num1}==${#num2)) && pad_ln=${#num1}
  # loop through bits
  for ((v=1; v<=pad_ln; v++)); do
    [[ $num1[$v] = $num2[$v] ]] && {
      out+='1'
    } || {
      out+='0'
    }
  done
  bin2dat "$out" "$outvar"
}

## bitwise AND
aland() {
  local num1="$1" num2="$2" outvar=${3:-al_return} cmp out
  local -i v pad_ln
  [[ -z "$num1" || -z "$num2" ]] && return 1
  # conv to binary
  dat2bin "$num1" num1
  dat2bin "$num2" num2
  # 0-pad to maxln if needed
  ((${#num1}>${#num2)) && {
    pad_ln=${#num1}
    num2="${(l:pad_ln::0:)num2}"
  }
  ((${#num1}<${#num2)) && {
    pad_ln=${#num2}
    num1="${(l:pad_ln::0:)num1}"
  }
  ((${#num1}==${#num2)) && pad_ln=${#num1}
  # loop through bits
  for ((v=1; v<=pad_ln; v++)); do
    [[ $num1[$v] = '1' && $num2[$v] = '1' ]] && {
      out+='1'
    } || {
      out+='0'
    }
  done
  bin2dat "$out" "$outvar"
}

## bitwise OR
alor() {
  local num1="$1" num2="$2" outvar=${3:-al_return} cmp out
  local -i v pad_ln
  [[ -z "$num1" || -z "$num2" ]] && return 1
  # conv to binary
  dat2bin "$num1" num1
  dat2bin "$num2" num2
  # 0-pad to maxln if needed
  ((${#num1}>${#num2)) && {
    pad_ln=${#num1}
    num2="${(l:pad_ln::0:)num2}"
  }
  ((${#num1}<${#num2)) && {
    pad_ln=${#num2}
    num1="${(l:pad_ln::0:)num1}"
  }
  ((${#num1}==${#num2)) && pad_ln=${#num1}
  # loop through bits
  for ((v=1; v<=pad_ln; v++)); do
    [[ $num1[$v] = '1' || $num2[$v] = '1' ]] && {
      out+='1'
    } || {
      out+='0'
    }
  done
  bin2dat "$out" "$outvar"
}

## bitwise NOR
alnor() {
  local num1="$1" num2="$2" outvar=${3:-al_return} cmp out
  local -i v pad_ln
  [[ -z "$num1" || -z "$num2" ]] && return 1
  # conv to binary
  dat2bin "$num1" num1
  dat2bin "$num2" num2
  # 0-pad to maxln if needed
  ((${#num1}>${#num2)) && {
    pad_ln=${#num1}
    num2="${(l:pad_ln::0:)num2}"
  }
  ((${#num1}<${#num2)) && {
    pad_ln=${#num2}
    num1="${(l:pad_ln::0:)num1}"
  }
  ((${#num1}==${#num2)) && pad_ln=${#num1}
  # loop through bits
  for ((v=1; v<=pad_ln; v++)); do
    [[ $num1[$v] = '0' && $num2[$v] = '0' ]] && {
      out+='1'
    } || {
      out+='0'
    }
  done
  bin2dat "$out" "$outvar"
}

## bitwise NAND
alnand() {
  local num1="$1" num2="$2" outvar=${3:-al_return} cmp out
  local -i v pad_ln
  [[ -z "$num1" || -z "$num2" ]] && return 1
  # conv to binary
  dat2bin "$num1" num1
  dat2bin "$num2" num2
  # 0-pad to maxln if needed
  ((${#num1}>${#num2)) && {
    pad_ln=${#num1}
    num2="${(l:pad_ln::0:)num2}"
  }
  ((${#num1}<${#num2)) && {
    pad_ln=${#num2}
    num1="${(l:pad_ln::0:)num1}"
  }
  ((${#num1}==${#num2)) && pad_ln=${#num1}
  # loop through bits
  for ((v=1; v<=pad_ln; v++)); do
    [[ $num1[$v] = '0' || $num2[$v] = '0' ]] && {
      out+='1'
    } || {
      out+='0'
    }
  done
  bin2dat "$out" "$outvar"
}

## bitwise NOT
alnot() {
  local num="$1" outvar=${2:-al_return} out
  local -i w
  [[ -z "$num" ]] && return 1
  dat2bin "$num" num
  for ((w=1; w<=${#num}; w++)); do
    [[ $num[$w] = '0' ]] && {
      out+='1'
    } || {
      out+='0'
    }
  done
  bin2dat "$out" "$outvar"
}
